### ISSUE TITLE
Updating a dish produces a server error

### ISSUE THREAD

**Issue by MarkusLeupold** [dboehmer/coocook#110]
Each time one triggers the "update dish" function from within a dishes view, the server responds with an error. This behaviour doesn't depend on which---if any---changes were made to the dish.

**Comment by dboehmer** [comment]
Thank you @MarkusLeupold  for submitting an issue! Your description was precise and very helpful. Good luck getting your job done&mdash;I look forward to enjoy your food on Saturday. :smiley:

This should be fixed by 66af1c2. @moseschmiedel Have a look at what a dump mistake we made :man_facepalming:

The fix is already deployed on Coocook.org. Can you confirm the issue is resolved?

**Comment by MarkusLeupold** [comment]
Confirmed. The issue is resolved.

**Comment by dboehmer** [comment]
Issue is not yet fixed. Of course this fails if `$item` is not defined:

```
                     if ( not( $item and $item->ingredients->exists ) ) {
                         $item->delete();
                         next;
                     }
```
